tap "nikitabobko/tap"
tap "FelixKratz/formulae"

brew "starship"
brew "eza"
brew "fzf"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "yazi"
brew "gh"
brew "duti"
brew "borders"
brew "sketchybar"

cask "nikitabobko/tap/aerospace"
cask "ghostty"
cask "obsidian"
cask "claude-code"
cask "citrix-workspace"
cask "font-jetbrains-mono-nerd-font"
cask "font-sketchybar-app-font"
